### ISSUE TITLE
No tag anymore

### ISSUE THREAD

**Issue by tillinger** [runderworld/ng-lodash#1]
Hey, 

it seems as if there's no TAG anymore?
with my bower.install I get the following error: 
`bower ng-lodash#~0                           ENORESTARGET No tag found that was able to satisfy ~0`

Any help here?

**Comment by Milutin85** [comment]
Hi there, same problem here :(
We can not build our application because of this error.

**Comment by runderworld** [comment]
@tillinger  @Milutin85  try again now.

**Comment by Milutin85** [comment]
@runderworld Hey it's working now, Thank you very much

**Comment by tillinger** [comment]
Yes thanks, it works again!  
-> Closing the issue..

**Comment by BraveThrasher** [comment]
What did you do that caused all the tags to be removed?
You should at least recreate ALL 10 previous tags.

**Comment by runderworld** [comment]
@BraveThrasher Unfortunately, I personally did nothing.   Up until two weeks ago, I was just a consumer of this lib like you. 

I emailed the original author of this repo that he had deleted this repo on GH, and that people downstream were affected.   

The original author and owner transferred ownership of the repo to me.

When the repo was transferred to me, apparently the git-tags were not preserved.  I manually recreated the ones I could immediately deduce from the commit trail.

My intention is to preserve the existing repo for several years to come until we all migrate off of this. 

If you know the rest of the missing tags and what commits they point at, please let me know. 

I will archive/freeze/lock (but NOT delete) the repo as soon as I restore the rest of the tags (assuming you provide this info).

**Comment by runderworld** [comment]
@BraveThrasher

*Update:*
I restored the 9 original tags as per [someone else's indirect fork](https://github.com/matthew-b-payne/ng-lodash/tags).

The 0.6.0 release was one performed by @matthew-b-payne after forking from an earlier copy/paste repo of rockabox's original.  

If you'd like to take advantage of his work, please feel free to continue with [his repo](https://github.com/matthew-b-payne/ng-lodash) or your fork of his repo.

I will be archiving this repo shortly, which is what the original author SHOULD HAVE done instead of deleting it outright.  My intent is to preserve the status quo for existing bower consumers of the original `rockabox/ng-lodash` lib (like me).
